### PR TITLE
Qt integration

### PR DESCRIPTION
**Pull request by IshoAntar**
<div align="center">

<h2>
	Here be dragons!
</h2>

<h4>The work for wxWidgets replacement is underway</h4>
</div>

Most of the codebase (read, every. single. file; almost) depends on wxwidgets
so it will require a significant amount of effort to replace everything.

The process, from what i see now, and from a high-level perspective,
will be done in two major steps:

1. Non-GUI controls
	These are wxwidgets classes that aren't directly related to the GUI
	but merely helper/utility classes, e.g. Threads, Timers, Atomics, MACROS

2. GUI controls and related classes
	These are interactible/renderable (not sure if those are words!) widgets,
	and related classes. i.e. Buttons, TextInputs, Events, EventHandlers

This will need to be done in incremental steps, so first
Non-GUI controls need to be scraped, either for standard library
equivalents, or Qt specific classes,
With the required conversions in the GUI layer, to adapt to wx data structures.

~~The GUI controls, since i (still) have no idea how to implement incrementally~~<sup>[1]</sup>
~~so that will have to wait for now. (Ideas welcome!)~~

<sup>[1]</sup>: I had the idea of using both! (temporarily) having two windows
and incrementally moving stuff from the wxWidgets' window to Qt's. That went ~~horribly wrong!~~ great! this is how the port will be carried out!

First we need to replace trivial wx dependent code, see checklist below.

`wxString` is off limits for now!
It's everywhere, and `QString` is *not* a drop-in replacement!
so surrounding code will need to be refactored, so it should be leaved
to the end, after the other stuff (From the first item in the checklist) are dealt with.

Also, i'm still not sure if there are parts where `wxString`
may be replaced with `std::string`, since `std::string` isn't Unicode aware,
and parts that need translation won't be able to make use of it (?)

---

After the above is dealt with...

We'll have to find a way to swap the GUI *and* the event-handling
of wx with those of Qt ~~which i still don't know how :(~~

~~We'll probably have to design the whole Qt (QML) GUI first,
refactor the event handling code into self contained (non-GUI dependent)
functions, then hook-up everything in the new GUI.~~ See <sup>[1]</sup> above!

- [x] Non-GUI controls
	- [x] `wxASSERT` -> `ASSERT` from the `Utils.h` header
	- [x] `wxASSERT_MSG` -> `ASSERT_WITH_MSG(x, msg)` from `Utils.h`
	- [x] `wxT` -> `TEXT` (Yes, stol..ahem borrowed from Unreal) from the `Utils.h` header
	- [x] `wxThread` -> `std::thread` from `<thread>` (might use `jthread`, when we support C++20) <sup>[1]</sup>
	- ~~[ ] `wxThreadHelper` Used in `src/effects/lv2/LV2Effect.h` -> ???~~
	- [x] `wxAtomic*` -> `std::atomic<*>` from `<atomic>`. Where `*` is any atomic type, `int`/`bool`/`whatever`
	- [x] `wxCondition` -> `std::condition_variable` from `<condition_variable>`
	- [x] `wxMutex` -> `std::mutex` from `<mutex>` <sup>[2]</sup>
	- [x] `wxUNUSED(x)` -> /* x */, this one just comments-out the argument's name
	- [x] `wxFAIL_MSG` -> `ASSERT_FAIL_WITH_MSG` from `Utils.h`
	- ~~[ ] `wxWeakRef` -> `std::weak_ptr` from `<memory>`~~. Used to hold wxWidgets types. Not worth it!
	- ~~[ ] `wxDynamicCast` -> `dynamic_cast<>()`~~. This is used to cast to wxWidgets controls types, that will be thrown away anyway. Probably not worth replacing.
	- Other stuff to be added as i come across them.

> <sup>[1]</sup> References to `wxThread` exist in `src/effects/Equalization48x.(h|cpp)`. The code is behind a preprocessor macro (disabled), and haven't been touched for a while. Not sure if it's worth messing with that (?).

> <sup>[2]</sup> wxMutexGui(Enter|Leave) are wxWidgets GUI controls specific and cannot be replaced.
> And same as <sup>[1]</sup>; It has references in the same file(s).

- [x] GUI Controls and related classes. *To be worked on in separate pull requests*
	- A list of controls can be found by running AudMonkey!
	  Everything on the main (wxWidgets) GUI will need to be ported to the QtQuick window.

### CODE REVIEW

**Comment by IshoAntar** [comment]
Alright, the `Install Qt` action on Windows is timing-out for some reason!
Too many commits?

**Comment by IshoAntar** [comment]
Why? because it's a lot of work, and the project will have to be rewritten almost entirely and I'm likely to screw things up?

**Comment by Paul-Licameli** [comment]
> Why? because it's a lot of work, and the project will have to be rewritten almost entirely and I'm likely to screw things up?

In my opinion, you are coding too much of the easy problem before you are planning enough first about the harder problems.  And all that change for the easy problem will only make pain if you want to keep downstreaming new good stuff too.

**Comment by IshoAntar** [comment]
> In my opinion, you are coding too much of the easy problem before you are planning enough first about the harder problems.

I will have to agree on this. But my lack of knowledge about the code base makes it hard to thoroughly plan ahead.
The work i'm doing here is helping me to better familiarize myself, though.

Also, Part of the work here (replacing wx stuff with the std equivalents, for example) will be merged in anyways, even if i abandon the port.

> And all that change for the easy problem will only make pain if you want to keep downstreaming new good stuff too.

This is not necessarily true. The modularization work that you're doing upstream should help counter this to some extent!
except the parts (of the modules) that still depend on wxWidgets, since my plan is to completely drop the dependency.

**Comment by Paul-Licameli** [comment]
Still at it, friend?  Good luck to you, but I think the temptation to make a sweeping cleanup up all the pervasive low level stuff like strings, in favor of std:: equivalents, should be resisted until late in the game.

**Comment by IshoAntar** [comment]
Yeah this is getting out of hand :/

So before i end up rewriting the whole thing, any pointers?

Starting from the other end, the top, handing over the event loop to Qt will break everything
and all of the wx controls will need to be ported one-by-one, essentially rewiring the whole GUI system
from scratch (which is to be expected, swapping the GUI toolkit isn't a simple task). This is what i had in mind, by the way.

The plan for the GUI, after i was done with this PR, which seems that it will take forever,
was something like..Make the (non-functional) GUI in QML first then wire it to the "back-end", porting the controls one by one, while making the necessary adjustments.

Doesn't seem terribly efficient, but worth a try :D. Plus, i get to learn how the underlying systems work (by breaking them!).

**Comment by IshoAntar** [comment]
Alright, here is some progress!

I've FINALLY got both wxWidgets *and* Qt windows running side-by-side!


> On the right is QtQuick and the left is the normal wxWidgets GUI. Ignore the colored squares :)

Both of them are responsive, caveats:

- The shutdown routine is messed up (it crashes!)
- I still need to test if calling internal routines works from both windows. It does from the main one, but not sure if the QtQuick window will cause trouble (no reason why it should, but still)

All that remains then is moving over everything from the wxWidgets window to the QtQuick window. Woohoo!

I'll clean some stuff up and push ASAP.

**Comment by IshoAntar** [comment]
OK my life has been a lie!

I've been messing with these event loops for hours and it turns
out that the only thing that a QtQuick application needs to run is the object?
I have absolutely no idea how the thing is processing the events (separate thread?),

this snippet is (somehow) enough to run the new window (copy-pasted from the Qt docs):
```C++
#if QT_VERSION < QT_VERSION_CHECK(6, 0, 0)
    QCoreApplication::setAttribute(Qt::AA_EnableHighDpiScaling);
#endif

   QGuiApplication app(argc, argv);

   QQmlApplicationEngine engine;
   const QUrl url(QStringLiteral("qrc:/main.qml"));
   QObject::connect(&engine, &QQmlApplicationEngine::objectCreated,
                  &app, [url](QObject *obj, const QUrl &objUrl) {
      if (!obj && url == objUrl)
         QCoreApplication::exit(-1);
   }, Qt::QueuedConnection);
   engine.load(url);
```

**Pull request merged**
